services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  grpc-server:
    build: ./grpc-server
    container_name: grpc_server
    volumes: 
      - ./data:/data/shared
    ports:
      - "50051:50051"
    depends_on:
      - mongo

  rest-api:
    build: ./rest-api
    container_name: rest_api
    ports:
      - "8080:8080"
    depends_on:
      - grpc-server
      - mongo

  flask-app:
    build: ./flask-app
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - rest-api

volumes:
  mongo-data: